### ISSUE TITLE
Cleanup community documentation

### ISSUE THREAD

**Issue by EddieTheCubeHead** [EddieTheCubeHead/ClusterBot#4]
- [x] Remove EddieTheCubeHead as the assignee for new tickets
- [x] Add a link to contribution guidelines into the README

**Comment by ayushmaanshrotriya** [comment]
will do

**Comment by ayushmaanshrotriya** [comment]
also where is the assignee for new tickets mentioned?

**Comment by EddieTheCubeHead** [comment]
.github/ISSUE_TEMPLATE/{template_name}.md, there's an "assignees" -row at the header space. Row should be empty after the ticket
